In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
iris = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\Iris.csv")
del iris['Id']
iris

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [23]:
iris_setosa = iris.iloc[0:50, 0:5]
iris_versicolor = iris.iloc[50:100, 0:5]
iris_virginica = iris.iloc[100:150, 0:5]

In [24]:
df1 = pd.DataFrame(iris_setosa.iloc[0:25, 0:5])
df2 = pd.DataFrame(iris_versicolor.iloc[0:25, 0:5])
df3 = pd.DataFrame(iris_virginica.iloc[0:25, 0:5])

In [25]:
iris_train = pd.concat([df1, df2, df3])
iris_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
120            6.9           3.2            5.7           2.3  Iris-virginica
121            5.6           2.8            4.9           2.0  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
123            6.3           2.7            4.9           1.8  Iris-virginica
124            6.7           3.3            5.7           2.1  Iris-virginica

[75 rows x 5 columns]

In [26]:
df1 = pd.DataFrame(iris_setosa.iloc[25:50, 0:5])
df2 = pd.DataFrame(iris_versicolor.iloc[25:50, 0:5])
df3 = pd.DataFrame(iris_virginica.iloc[25:50, 0:5])

In [27]:
iris_test = pd.concat([df1, df2, df3])
iris_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
25             5.0           3.0            1.6           0.2     Iris-setosa
26             5.0           3.4            1.6           0.4     Iris-setosa
27             5.2           3.5            1.5           0.2     Iris-setosa
28             5.2           3.4            1.4           0.2     Iris-setosa
29             4.7           3.2            1.6           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[75 rows x 5 columns]

In [28]:
X_train = iris_train.iloc[:, 0:4]
y_train = iris_train.iloc[:, 4]
X_test = iris_test.iloc[:, 0:4]
y_test = iris_test.iloc[:, 4]

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [30]:
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype=object)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.92

In [32]:
# To find the default parameters of the model
classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}